"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge, Panel, ScoreRing, SectionTitle, SignalCard, StatCard, TradingViewChart, ZoneCard, money, type Analysis, type Quote } from "../components/gsat/ui";

type QuoteResponse = { quotes: Quote[]; updatedAt: string; spotError?: string | null };
type AnalysisResponse = { source?: string; generatedAt?: string; gold: { intraday: Analysis }; silver: { intraday: Analysis }; methodology?: { note?: string } };

const statusFromQuotes = (q: Quote[]) => { const stamps = q.filter(x => x.providerUpdatedAt).map(x => Date.parse(x.providerUpdatedAt as string)); const latest = stamps.length ? Math.max(...stamps) : NaN; if (!Number.isFinite(latest)) return { label: "DATA STATUS UNKNOWN", detail: "Waiting for spot timestamp" }; const age = Math.max(0, Date.now()-latest)/1000; return age <= 90 ? { label:"SPOT DATA FRESH", detail:`Updated ${Math.round(age)}s ago` } : { label:"SPOT DATA STALE", detail:`Last update ${Math.round(age/60)}m ago` }; };
const biasTone = (bias:string): "green"|"red"|"gold" => /bull|buy/i.test(bias) ? "green" : /bear|sell/i.test(bias) ? "red" : "gold";
const technicalScore = (a:Analysis|null) => { if(!a) return 50; const base = /bull|buy/i.test(a.overall?.bias ?? "") ? 68 : /bear|sell/i.test(a.overall?.bias ?? "") ? 32 : 50; const r = a.momentum.rsi14 == null ? 0 : a.momentum.rsi14 > 50 ? 8 : -8; const m = a.momentum.macdHistogram == null ? 0 : a.momentum.macdHistogram > 0 ? 9 : -9; return Math.max(0,Math.min(100,Math.round(base+r+m))); };

function BiasPanel({metal,a}:{metal:string;a:Analysis|null}) { const bias=a?.overall?.bias??"Loading"; const tone=biasTone(bias); const score=technicalScore(a); return <Panel className="p-5 sm:p-6"><SectionTitle eyebrow={`${metal.toUpperCase()} INTELLIGENCE`} title="Market Bias Score" detail="EMA + RSI + MACD"/><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="flex items-center gap-5"><ScoreRing score={score} label="/100" tone={tone}/><div><Badge tone={tone}>{bias}</Badge><p className="mt-2 text-sm font-bold text-slate-200">GSAT technical confidence</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-500">Visual summary of the existing technical engine. Not a guaranteed prediction.</p></div></div><div className="grid flex-1 gap-3 sm:grid-cols-3"><StatCard label="RSI 14" value={a?.momentum.rsi14==null?"--":a.momentum.rsi14.toFixed(2)} sub={a?.momentum.rsiBias??"Loading"} tone={a?.momentum.rsi14!=null&&a.momentum.rsi14>50?"green":"gold"}/><StatCard label="MACD" value={a?.momentum.macdBias??"--"} sub={`Hist ${a?.momentum.macdHistogram?.toFixed(4)??"--"}`} tone={a?.momentum.macdHistogram!=null&&a.momentum.macdHistogram>0?"green":"gold"}/><StatCard label="TREND" value={a?.ema.bias??"--"} sub={a?.ema.interpretation??"Trend state"} tone={tone}/></div></div></Panel>; }

function EmaPanel({metal,a}:{metal:string;a:Analysis|null}) { const rows = a ? [["EMA 20",a.ema.ema20,a.ema.priceVsEma20,"Short-term"],["EMA 50",a.ema.ema50,a.ema.priceVsEma50,"Medium-term"],["EMA 200",a.ema.ema200,a.ema.priceVsEma200,"Long-term"]] as const : []; return <Panel className="p-5 sm:p-6"><SectionTitle eyebrow="TREND ENGINE" title={`${metal} EMA Dashboard`} detail="20 / 50 / 200"/><div className="grid gap-3 md:grid-cols-3">{rows.length?rows.map(([label,value,rel,term])=><StatCard key={label} label={label} value={money(value)} sub={`${term} • Price ${money(a?.price??null)}`} tone={rel==="Above"?"green":rel==="Below"?"red":"gold"} badge={rel}/>):<div className="md:col-span-3 rounded-2xl border border-slate-700 bg-[#081321] p-6 text-sm text-slate-400">Loading EMA values…</div>}</div><p className="mt-4 rounded-2xl border border-slate-700/70 bg-[#081321] p-4 text-sm leading-6 text-slate-300">{a?.ema.interpretation??"EMA interpretation will appear when the technical engine returns data."}</p></Panel>; }

function MomentumPanel({metal,a}:{metal:string;a:Analysis|null}) { return <Panel className="p-5 sm:p-6"><SectionTitle eyebrow="MOMENTUM ENGINE" title={`${metal} RSI + MACD Intelligence`} detail="14 / 12-26-9"/><div className="grid gap-3 md:grid-cols-2"><StatCard label="RSI 14" value={a?.momentum.rsi14==null?"--":a.momentum.rsi14.toFixed(2)} sub={a?.momentum.rsiBias??"Loading"} tone={a?.momentum.rsi14!=null&&a.momentum.rsi14>50?"green":"gold"}/><StatCard label="MACD 12/26/9" value={a?.momentum.macd==null?"--":a.momentum.macd.toFixed(4)} sub={`Signal ${a?.momentum.macdSignal?.toFixed(4)??"--"} • Hist ${a?.momentum.macdHistogram?.toFixed(4)??"--"}`} tone={a?.momentum.macdHistogram!=null&&a.momentum.macdHistogram>0?"green":"gold"}/></div><div className="mt-4 rounded-2xl border border-slate-700/70 bg-[#081321] p-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">GSAT READ</p><p className="mt-2 text-sm leading-6 text-slate-300">{a?.momentum.interpretation??"Momentum interpretation will appear with live analysis."}</p></div></Panel>; }

function SrPanel({metal,a}:{metal:string;a:Analysis|null}) { return <Panel className="p-5 sm:p-6"><SectionTitle eyebrow="LEVEL ENGINE" title={`${metal} Support & Resistance`} detail="Nearest → major"/><div className="grid gap-3 lg:grid-cols-2"><ZoneCard title="SUPPORT ZONES" levels={(a?.supportResistance.supports??[]).slice(0,3)} kind="support"/><ZoneCard title="RESISTANCE ZONES" levels={(a?.supportResistance.resistances??[]).slice(0,3)} kind="resistance"/></div></Panel>; }

function MultiTimeframe(){ const rows=[["15 MIN","Near-term"],["1 HOUR","Intraday"],["4 HOUR","Swing"],["DAILY","Primary"],["WEEKLY","Macro"]]; return <Panel className="overflow-hidden"><div className="p-5 sm:p-6"><SectionTitle eyebrow="MARKET STRUCTURE" title="Multi-Timeframe Levels" detail="Framework ready for multi-series calculation"/><div className="overflow-x-auto rounded-2xl border border-slate-700/70"><table className="min-w-full text-left text-sm"><thead className="bg-[#081321] text-[10px] uppercase tracking-[0.16em] text-slate-500"><tr><th className="px-4 py-3">Timeframe</th><th className="px-4 py-3">Horizon</th><th className="px-4 py-3">Support</th><th className="px-4 py-3">Resistance</th></tr></thead><tbody>{rows.map(([tf,h])=><tr key={tf} className="border-t border-slate-800/80"><td className="px-4 py-3 font-bold text-slate-200">{tf}</td><td className="px-4 py-3 text-slate-500">{h}</td><td className="px-4 py-3 text-emerald-300">Engine ready</td><td className="px-4 py-3 text-rose-300">Engine ready</td></tr>)}</tbody></table></div></div></Panel>; }

function TradePlan({metal,a}:{metal:string;a:Analysis|null}) { const s=a?.supportResistance.supports?.[0]; const r=a?.supportResistance.resistances?.[0]; const sp=typeof s==="number"?s:s?.price; const rp=typeof r==="number"?r:r?.price; const bullish=/bull|buy/i.test(a?.overall?.bias??""); return <Panel className="p-5 sm:p-6"><SectionTitle eyebrow="DECISION LAYER" title={`${metal} Trade Plan`} detail="Technical framework"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><SignalCard label="BIAS" value={a?.overall?.bias??"Loading"} detail={a?.overall?.summary??"Current technical summary."} tone={bullish?"green":"gold"}/><SignalCard label="BUY / WATCH ZONE" value={sp!=null?money(sp):"--"} detail="Nearest modeled support." tone="green"/><SignalCard label="RESISTANCE WATCH" value={rp!=null?money(rp):"--"} detail="Nearest modeled resistance." tone="red"/><SignalCard label="CONFIDENCE" value={`${technicalScore(a)}/100`} detail="Technical-state score only." tone={bullish?"green":"gold"}/></div></Panel>; }

export default function GsatV2Page(){ const [data,setData]=useState<QuoteResponse>({quotes:[],updatedAt:""}); const [analysis,setAnalysis]=useState<AnalysisResponse|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const load=useCallback(async()=>{try{setLoading(true);setError("");const q=await fetch(`/api/quotes?fresh=${Date.now()}`,{cache:"no-store"});if(!q.ok)throw new Error("Live spot request failed");const qd=await q.json() as QuoteResponse;setData(qd);const a=await fetch(`/api/analysis?hours=72&fresh=${Date.now()}`,{cache:"no-store"});const ad=await a.json();if(!a.ok)throw new Error(ad?.error||"Technical analysis unavailable");setAnalysis(ad as AnalysisResponse);}catch(e){setError(e instanceof Error?e.message:"Live market data unavailable");}finally{setLoading(false);}},[]); useEffect(()=>{void load();const t=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(t);},[load]); const gold=data.quotes.find(q=>q.label==="Gold"); const silver=data.quotes.find(q=>q.label==="Silver"); const ratio=gold&&silver&&silver.price>0?gold.price/silver.price:null; const status=useMemo(()=>statusFromQuotes(data.quotes),[data.quotes]); const ga=analysis?.gold.intraday??null; const sa=analysis?.silver.intraday??null;
return <main className="min-h-screen bg-[#050b16] text-slate-100"><div className="mx-auto max-w-[1500px] px-3 py-3 sm:px-5 sm:py-5"><header className="rounded-3xl border border-slate-700/80 bg-[linear-gradient(135deg,#0d1c30,#07121f)] p-5 shadow-2xl shadow-black/30 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-black tracking-[0.36em] text-amber-300">GSAT</p><Badge tone="green">LIVE TERMINAL</Badge><Badge tone="blue">XAU/USD • XAG/USD</Badge></div><h1 className="mt-3 text-3xl font-black tracking-tight text-white sm:text-4xl">Gold & Silver Analysis Terminal</h1><p className="mt-2 text-sm text-slate-400">Spot market • Technical intelligence • TradingView</p></div><div className="flex flex-wrap items-center gap-2"><Badge tone={status.label.includes("FRESH")?"green":"gold"}>{status.label}</Badge><span className="rounded-full border border-slate-700 bg-[#07101c] px-3 py-2 text-xs text-slate-400">{status.detail}</span><button onClick={()=>void load()} className="rounded-xl border border-amber-300/30 bg-amber-300/10 px-4 py-2 text-sm font-extrabold text-amber-200">{loading?"Refreshing…":"Refresh"}</button></div></div></header>
<section className="mt-4 grid gap-3 lg:grid-cols-3"><StatCard label="GOLD SPOT / USD" value={money(gold?.price??null)} sub={`XAUS • ${gold?.providerUpdatedAt?new Date(gold.providerUpdatedAt).toLocaleTimeString("en-IN"):"--"}`} tone="gold" badge="LIVE"/><StatCard label="SILVER SPOT / USD" value={money(silver?.price??null)} sub={`XAUS • ${silver?.providerUpdatedAt?new Date(silver.providerUpdatedAt).toLocaleTimeString("en-IN"):"--"}`} tone="blue" badge="LIVE"/><StatCard label="GOLD / SILVER RATIO" value={ratio==null?"--":ratio.toFixed(2)} sub="Calculated from live XAUS spot quotes" tone="muted" badge="CALCULATED"/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><TradingViewChart symbol="OANDA:XAUUSD" title="GOLD SPOT / USD"/><TradingViewChart symbol="OANDA:XAGUSD" title="SILVER SPOT / USD"/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><BiasPanel metal="Gold" a={ga}/><BiasPanel metal="Silver" a={sa}/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><EmaPanel metal="Gold" a={ga}/><EmaPanel metal="Silver" a={sa}/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><SrPanel metal="Gold" a={ga}/><SrPanel metal="Silver" a={sa}/></section>
<section className="mt-4"><MultiTimeframe/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><MomentumPanel metal="Gold" a={ga}/><MomentumPanel metal="Silver" a={sa}/></section>
<section className="mt-4 grid gap-4 xl:grid-cols-2"><TradePlan metal="Gold" a={ga}/><TradePlan metal="Silver" a={sa}/></section>
<section className="mt-4 grid gap-4 md:grid-cols-3"><SignalCard label="MACRO DASHBOARD" value="READY" detail="Reserved for verified macro inputs: DXY, yields, policy and inflation." tone="blue"/><SignalCard label="PATTERN ENGINE" value="READY" detail="Reserved for confirmed price-structure pattern inputs." tone="gold"/><SignalCard label="HISTORICAL VIEW" value="READY" detail="Reserved for timeframe-specific historical analysis." tone="muted"/></section>
{(error||data.spotError)?<div className="mt-4 rounded-2xl border border-rose-400/20 bg-rose-400/[0.05] p-4 text-xs text-rose-300">{error||data.spotError}</div>:null}<footer className="mt-5 border-t border-slate-800/80 pt-4 text-[10px] tracking-[0.14em] text-slate-600">GSAT • XAUS SPOT • TRADINGVIEW/OANDA • TECHNICAL ENGINE • UI V2</footer></div></main>;
}
